FROM python:3.12-alpine

WORKDIR /tests/test_api

COPY . /tests/test_api/

RUN apk update && \
    apk add --no-cache bash && \
    pip install --no-cache-dir -r requirements.txt

COPY run_tests.sh run_tests.sh

RUN chmod +x run_tests.sh

CMD ["./run_tests.sh"]

# To build Dockerfile: docker build -f Dockerfile.test -t rest-api-app-test .
# To run the container: docker run --rm rest-api-app-test