name: Run and Test API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:7.1.0
        options: --privileged
        ports:
          - 5000:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/checkout@v2
      with:
        python-version: '3.12'

    - name: Build image for API
      run: docker build -t rest-api-app

    - name: Run tests
      run: docker run rest-api-app-test
